version: '3'
services:
  app:
    container_name: spring_boot_app
    build: ./
    ports:
     - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/user_management

  mysql:
    image: mysql:8.1.0
    ports:
      - "3307:3036"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root@123


